# Generated by Django 4.0.5 on 2022-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=2000)),
                ('short_url', models.CharField(max_length=25)),
                ('created_on', models.DateTimeField()),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
